// 国际电话区号列表（150+ 国家）
export interface CountryCode {
  code: string;   // ISO 3166-1 alpha-2
  dial: string;   // 区号（如 +60）
  name: string;   // 英文名
  flag: string;   // emoji 国旗
}

export const COUNTRY_CODES: CountryCode[] = [
  { code: 'MY', dial: '+60', name: 'Malaysia', flag: '🇲🇾' },
  { code: 'CN', dial: '+86', name: 'China', flag: '🇨🇳' },
  { code: 'US', dial: '+1', name: 'United States', flag: '🇺🇸' },
  { code: 'SG', dial: '+65', name: 'Singapore', flag: '🇸🇬' },
  { code: 'JP', dial: '+81', name: 'Japan', flag: '🇯🇵' },
  { code: 'KR', dial: '+82', name: 'South Korea', flag: '🇰🇷' },
  { code: 'TH', dial: '+66', name: 'Thailand', flag: '🇹🇭' },
  { code: 'ID', dial: '+62', name: 'Indonesia', flag: '🇮🇩' },
  { code: 'PH', dial: '+63', name: 'Philippines', flag: '🇵🇭' },
  { code: 'VN', dial: '+84', name: 'Vietnam', flag: '🇻🇳' },
  { code: 'IN', dial: '+91', name: 'India', flag: '🇮🇳' },
  { code: 'GB', dial: '+44', name: 'United Kingdom', flag: '🇬🇧' },
  { code: 'DE', dial: '+49', name: 'Germany', flag: '🇩🇪' },
  { code: 'FR', dial: '+33', name: 'France', flag: '🇫🇷' },
  { code: 'ES', dial: '+34', name: 'Spain', flag: '🇪🇸' },
  { code: 'IT', dial: '+39', name: 'Italy', flag: '🇮🇹' },
  { code: 'RU', dial: '+7', name: 'Russia', flag: '🇷🇺' },
  { code: 'BR', dial: '+55', name: 'Brazil', flag: '🇧🇷' },
  { code: 'AU', dial: '+61', name: 'Australia', flag: '🇦🇺' },
  { code: 'CA', dial: '+1', name: 'Canada', flag: '🇨🇦' },
  { code: 'TW', dial: '+886', name: 'Taiwan', flag: '🇹🇼' },
  { code: 'HK', dial: '+852', name: 'Hong Kong', flag: '🇭🇰' },
  { code: 'MO', dial: '+853', name: 'Macau', flag: '🇲🇴' },
  { code: 'NZ', dial: '+64', name: 'New Zealand', flag: '🇳🇿' },
  { code: 'MX', dial: '+52', name: 'Mexico', flag: '🇲🇽' },
  { code: 'AR', dial: '+54', name: 'Argentina', flag: '🇦🇷' },
  { code: 'CL', dial: '+56', name: 'Chile', flag: '🇨🇱' },
  { code: 'CO', dial: '+57', name: 'Colombia', flag: '🇨🇴' },
  { code: 'PE', dial: '+51', name: 'Peru', flag: '🇵🇪' },
  { code: 'VE', dial: '+58', name: 'Venezuela', flag: '🇻🇪' },
  { code: 'EC', dial: '+593', name: 'Ecuador', flag: '🇪🇨' },
  { code: 'BO', dial: '+591', name: 'Bolivia', flag: '🇧🇴' },
  { code: 'PY', dial: '+595', name: 'Paraguay', flag: '🇵🇾' },
  { code: 'UY', dial: '+598', name: 'Uruguay', flag: '🇺🇾' },
  { code: 'CR', dial: '+506', name: 'Costa Rica', flag: '🇨🇷' },
  { code: 'PA', dial: '+507', name: 'Panama', flag: '🇵🇦' },
  { code: 'CU', dial: '+53', name: 'Cuba', flag: '🇨🇺' },
  { code: 'DO', dial: '+1', name: 'Dominican Republic', flag: '🇩🇴' },
  { code: 'GT', dial: '+502', name: 'Guatemala', flag: '🇬🇹' },
  { code: 'HN', dial: '+504', name: 'Honduras', flag: '🇭🇳' },
  { code: 'NI', dial: '+505', name: 'Nicaragua', flag: '🇳🇮' },
  { code: 'SV', dial: '+503', name: 'El Salvador', flag: '🇸🇻' },
  { code: 'PT', dial: '+351', name: 'Portugal', flag: '🇵🇹' },
  { code: 'NL', dial: '+31', name: 'Netherlands', flag: '🇳🇱' },
  { code: 'BE', dial: '+32', name: 'Belgium', flag: '🇧🇪' },
  { code: 'CH', dial: '+41', name: 'Switzerland', flag: '🇨🇭' },
  { code: 'AT', dial: '+43', name: 'Austria', flag: '🇦🇹' },
  { code: 'SE', dial: '+46', name: 'Sweden', flag: '🇸🇪' },
  { code: 'NO', dial: '+47', name: 'Norway', flag: '🇳🇴' },
  { code: 'DK', dial: '+45', name: 'Denmark', flag: '🇩🇰' },
  { code: 'FI', dial: '+358', name: 'Finland', flag: '🇫🇮' },
  { code: 'PL', dial: '+48', name: 'Poland', flag: '🇵🇱' },
  { code: 'CZ', dial: '+420', name: 'Czech Republic', flag: '🇨🇿' },
  { code: 'SK', dial: '+421', name: 'Slovakia', flag: '🇸🇰' },
  { code: 'HU', dial: '+36', name: 'Hungary', flag: '🇭🇺' },
  { code: 'RO', dial: '+40', name: 'Romania', flag: '🇷🇴' },
  { code: 'BG', dial: '+359', name: 'Bulgaria', flag: '🇧🇬' },
  { code: 'HR', dial: '+385', name: 'Croatia', flag: '🇭🇷' },
  { code: 'RS', dial: '+381', name: 'Serbia', flag: '🇷🇸' },
  { code: 'SI', dial: '+386', name: 'Slovenia', flag: '🇸🇮' },
  { code: 'BA', dial: '+387', name: 'Bosnia', flag: '🇧🇦' },
  { code: 'MK', dial: '+389', name: 'North Macedonia', flag: '🇲🇰' },
  { code: 'AL', dial: '+355', name: 'Albania', flag: '🇦🇱' },
  { code: 'GR', dial: '+30', name: 'Greece', flag: '🇬🇷' },
  { code: 'TR', dial: '+90', name: 'Turkey', flag: '🇹🇷' },
  { code: 'UA', dial: '+380', name: 'Ukraine', flag: '🇺🇦' },
  { code: 'BY', dial: '+375', name: 'Belarus', flag: '🇧🇾' },
  { code: 'LT', dial: '+370', name: 'Lithuania', flag: '🇱🇹' },
  { code: 'LV', dial: '+371', name: 'Latvia', flag: '🇱🇻' },
  { code: 'EE', dial: '+372', name: 'Estonia', flag: '🇪🇪' },
  { code: 'IE', dial: '+353', name: 'Ireland', flag: '🇮🇪' },
  { code: 'IS', dial: '+354', name: 'Iceland', flag: '🇮🇸' },
  { code: 'LU', dial: '+352', name: 'Luxembourg', flag: '🇱🇺' },
  { code: 'MT', dial: '+356', name: 'Malta', flag: '🇲🇹' },
  { code: 'CY', dial: '+357', name: 'Cyprus', flag: '🇨🇾' },
  { code: 'GE', dial: '+995', name: 'Georgia', flag: '🇬🇪' },
  { code: 'AM', dial: '+374', name: 'Armenia', flag: '🇦🇲' },
  { code: 'AZ', dial: '+994', name: 'Azerbaijan', flag: '🇦🇿' },
  { code: 'KZ', dial: '+7', name: 'Kazakhstan', flag: '🇰🇿' },
  { code: 'UZ', dial: '+998', name: 'Uzbekistan', flag: '🇺🇿' },
  { code: 'TM', dial: '+993', name: 'Turkmenistan', flag: '🇹🇲' },
  { code: 'KG', dial: '+996', name: 'Kyrgyzstan', flag: '🇰🇬' },
  { code: 'TJ', dial: '+992', name: 'Tajikistan', flag: '🇹🇯' },
  { code: 'MN', dial: '+976', name: 'Mongolia', flag: '🇲🇳' },
  { code: 'KH', dial: '+855', name: 'Cambodia', flag: '🇰🇭' },
  { code: 'LA', dial: '+856', name: 'Laos', flag: '🇱🇦' },
  { code: 'MM', dial: '+95', name: 'Myanmar', flag: '🇲🇲' },
  { code: 'BD', dial: '+880', name: 'Bangladesh', flag: '🇧🇩' },
  { code: 'LK', dial: '+94', name: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'NP', dial: '+977', name: 'Nepal', flag: '🇳🇵' },
  { code: 'PK', dial: '+92', name: 'Pakistan', flag: '🇵🇰' },
  { code: 'AF', dial: '+93', name: 'Afghanistan', flag: '🇦🇫' },
  { code: 'IR', dial: '+98', name: 'Iran', flag: '🇮🇷' },
  { code: 'IQ', dial: '+964', name: 'Iraq', flag: '🇮🇶' },
  { code: 'SA', dial: '+966', name: 'Saudi Arabia', flag: '🇸🇦' },
  { code: 'AE', dial: '+971', name: 'UAE', flag: '🇦🇪' },
  { code: 'QA', dial: '+974', name: 'Qatar', flag: '🇶🇦' },
  { code: 'KW', dial: '+965', name: 'Kuwait', flag: '🇰🇼' },
  { code: 'BH', dial: '+973', name: 'Bahrain', flag: '🇧🇭' },
  { code: 'OM', dial: '+968', name: 'Oman', flag: '🇴🇲' },
  { code: 'YE', dial: '+967', name: 'Yemen', flag: '🇾🇪' },
  { code: 'JO', dial: '+962', name: 'Jordan', flag: '🇯🇴' },
  { code: 'LB', dial: '+961', name: 'Lebanon', flag: '🇱🇧' },
  { code: 'SY', dial: '+963', name: 'Syria', flag: '🇸🇾' },
  { code: 'PS', dial: '+970', name: 'Palestine', flag: '🇵🇸' },
  { code: 'IL', dial: '+972', name: 'Israel', flag: '🇮🇱' },
  { code: 'EG', dial: '+20', name: 'Egypt', flag: '🇪🇬' },
  { code: 'MA', dial: '+212', name: 'Morocco', flag: '🇲🇦' },
  { code: 'DZ', dial: '+213', name: 'Algeria', flag: '🇩🇿' },
  { code: 'TN', dial: '+216', name: 'Tunisia', flag: '🇹🇳' },
  { code: 'LY', dial: '+218', name: 'Libya', flag: '🇱🇾' },
  { code: 'NG', dial: '+234', name: 'Nigeria', flag: '🇳🇬' },
  { code: 'GH', dial: '+233', name: 'Ghana', flag: '🇬🇭' },
  { code: 'KE', dial: '+254', name: 'Kenya', flag: '🇰🇪' },
  { code: 'TZ', dial: '+255', name: 'Tanzania', flag: '🇹🇿' },
  { code: 'UG', dial: '+256', name: 'Uganda', flag: '🇺🇬' },
  { code: 'ET', dial: '+251', name: 'Ethiopia', flag: '🇪🇹' },
  { code: 'ZA', dial: '+27', name: 'South Africa', flag: '🇿🇦' },
  { code: 'CM', dial: '+237', name: 'Cameroon', flag: '🇨🇲' },
  { code: 'CI', dial: '+225', name: 'Ivory Coast', flag: '🇨🇮' },
  { code: 'SN', dial: '+221', name: 'Senegal', flag: '🇸🇳' },
  { code: 'CD', dial: '+243', name: 'DR Congo', flag: '🇨🇩' },
  { code: 'AO', dial: '+244', name: 'Angola', flag: '🇦🇴' },
  { code: 'MZ', dial: '+258', name: 'Mozambique', flag: '🇲🇿' },
  { code: 'MG', dial: '+261', name: 'Madagascar', flag: '🇲🇬' },
  { code: 'ZW', dial: '+263', name: 'Zimbabwe', flag: '🇿🇼' },
  { code: 'ZM', dial: '+260', name: 'Zambia', flag: '🇿🇲' },
  { code: 'RW', dial: '+250', name: 'Rwanda', flag: '🇷🇼' },
  { code: 'SD', dial: '+249', name: 'Sudan', flag: '🇸🇩' },
  { code: 'ML', dial: '+223', name: 'Mali', flag: '🇲🇱' },
  { code: 'BF', dial: '+226', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'NE', dial: '+227', name: 'Niger', flag: '🇳🇪' },
  { code: 'TD', dial: '+235', name: 'Chad', flag: '🇹🇩' },
  { code: 'BN', dial: '+673', name: 'Brunei', flag: '🇧🇳' },
  { code: 'FJ', dial: '+679', name: 'Fiji', flag: '🇫🇯' },
  { code: 'PG', dial: '+675', name: 'Papua New Guinea', flag: '🇵🇬' },
  { code: 'WS', dial: '+685', name: 'Samoa', flag: '🇼🇸' },
  { code: 'TO', dial: '+676', name: 'Tonga', flag: '🇹🇴' },
  { code: 'JM', dial: '+1', name: 'Jamaica', flag: '🇯🇲' },
  { code: 'TT', dial: '+1', name: 'Trinidad & Tobago', flag: '🇹🇹' },
  { code: 'BB', dial: '+1', name: 'Barbados', flag: '🇧🇧' },
  { code: 'HT', dial: '+509', name: 'Haiti', flag: '🇭🇹' },
  { code: 'PR', dial: '+1', name: 'Puerto Rico', flag: '🇵🇷' },
  { code: 'BZ', dial: '+501', name: 'Belize', flag: '🇧🇿' },
  { code: 'GY', dial: '+592', name: 'Guyana', flag: '🇬🇾' },
  { code: 'SR', dial: '+597', name: 'Suriname', flag: '🇸🇷' },
  { code: 'MD', dial: '+373', name: 'Moldova', flag: '🇲🇩' },
  { code: 'ME', dial: '+382', name: 'Montenegro', flag: '🇲🇪' },
  { code: 'XK', dial: '+383', name: 'Kosovo', flag: '🇽🇰' },
  { code: 'AD', dial: '+376', name: 'Andorra', flag: '🇦🇩' },
  { code: 'MC', dial: '+377', name: 'Monaco', flag: '🇲🇨' },
  { code: 'LI', dial: '+423', name: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'SM', dial: '+378', name: 'San Marino', flag: '🇸🇲' },
];

// 根据浏览器语言猜测默认国家
const LANG_COUNTRY_MAP: Record<string, string> = {
  'zh-CN': 'CN', 'zh-TW': 'TW', 'zh-HK': 'HK', 'zh': 'CN',
  'en-US': 'US', 'en-GB': 'GB', 'en-AU': 'AU', 'en-MY': 'MY', 'en': 'US',
  'ms': 'MY', 'ms-MY': 'MY',
  'ja': 'JP', 'ko': 'KR', 'th': 'TH', 'vi': 'VN', 'id': 'ID',
  'de': 'DE', 'fr': 'FR', 'es': 'ES', 'it': 'IT', 'pt': 'PT', 'pt-BR': 'BR',
  'ru': 'RU', 'ar': 'SA', 'hi': 'IN', 'bn': 'BD', 'tr': 'TR',
  'nl': 'NL', 'pl': 'PL', 'sv': 'SE', 'da': 'DK', 'fi': 'FI', 'no': 'NO',
  'el': 'GR', 'cs': 'CZ', 'ro': 'RO', 'hu': 'HU', 'uk': 'UA',
};

export function getDefaultCountry(): string {
  if (typeof navigator === 'undefined') return 'MY';
  const lang = navigator.language || 'en';
  return LANG_COUNTRY_MAP[lang] || LANG_COUNTRY_MAP[lang.split('-')[0]] || 'MY';
}
